package store

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/edaywalid/sched/internal/store/db"
)

// PostgresStore persists workflow state in PostgreSQL via a pgx pool.
// Queries are generated by sqlc from internal/store/queries/*.sql.
type PostgresStore struct {
	pool    *pgxpool.Pool
	queries *db.Queries
}

func NewPostgresStore(ctx context.Context, dsn string) (*PostgresStore, error) {
	pool, err := pgxpool.New(ctx, dsn)
	if err != nil {
		return nil, fmt.Errorf("open pgx pool: %w", err)
	}
	if err := pool.Ping(ctx); err != nil {
		pool.Close()
		return nil, fmt.Errorf("ping postgres: %w", err)
	}
	return &PostgresStore{pool: pool, queries: db.New(pool)}, nil
}

func (p *PostgresStore) Pool() *pgxpool.Pool { return p.pool }

func (p *PostgresStore) Close() error {
	p.pool.Close()
	return nil
}

func (p *PostgresStore) CreateWorkflow(ctx context.Context, wf Workflow) error {
	startTime := wf.StartTime
	if startTime.IsZero() {
		startTime = time.Now()
	}
	status := wf.Status
	if status == "" {
		status = StatusRunning
	}
	version := wf.Version
	if version == 0 {
		version = 1
	}
	err := p.queries.CreateWorkflow(ctx, db.CreateWorkflowParams{
		WorkflowID: wf.WorkflowID,
		RunID:      wf.RunID,
		Name:       wf.Name,
		Status:     string(status),
		Input:      wf.Input,
		StartTime:  pgtype.Timestamptz{Time: startTime, Valid: true},
		Version:    int32(version),
	})
	if err != nil {
		return fmt.Errorf("create workflow: %w", err)
	}
	return nil
}

func (p *PostgresStore) AppendEvent(ctx context.Context, ev Event) error {
	tx, err := p.pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("begin tx: %w", err)
	}
	defer tx.Rollback(ctx)

	q := p.queries.WithTx(tx)

	if err := assertWorkflowExists(ctx, tx, ev.WorkflowID); err != nil {
		return err
	}

	if _, err := q.AppendEvent(ctx, db.AppendEventParams{
		WorkflowID: ev.WorkflowID,
		EventType:  ev.Type,
		Details:    ev.Details,
	}); err != nil {
		return fmt.Errorf("append event: %w", err)
	}

	if err := q.BumpVersion(ctx, ev.WorkflowID); err != nil {
		return fmt.Errorf("bump version: %w", err)
	}

	if err := tx.Commit(ctx); err != nil {
		return fmt.Errorf("commit: %w", err)
	}
	return nil
}

func (p *PostgresStore) CompleteWorkflow(ctx context.Context, workflowID string, status WorkflowStatus, result []byte, errMsg string) error {
	if err := assertWorkflowExists(ctx, p.pool, workflowID); err != nil {
		return err
	}
	err := p.queries.CompleteWorkflow(ctx, db.CompleteWorkflowParams{
		WorkflowID: workflowID,
		Status:     string(status),
		Result:     result,
		Error:      errMsg,
	})
	if err != nil {
		return fmt.Errorf("complete workflow: %w", err)
	}
	return nil
}

func (p *PostgresStore) GetWorkflow(ctx context.Context, workflowID string) (*Workflow, error) {
	row, err := p.queries.GetWorkflow(ctx, workflowID)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, ErrWorkflowNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("get workflow: %w", err)
	}
	wf := workflowFromRow(row)
	return &wf, nil
}

func (p *PostgresStore) GetHistory(ctx context.Context, workflowID string) ([]Event, error) {
	if err := assertWorkflowExists(ctx, p.pool, workflowID); err != nil {
		return nil, err
	}
	rows, err := p.queries.GetHistory(ctx, workflowID)
	if err != nil {
		return nil, fmt.Errorf("get history: %w", err)
	}
	out := make([]Event, 0, len(rows))
	for _, r := range rows {
		out = append(out, Event{
			Idx:        r.Idx,
			WorkflowID: r.WorkflowID,
			Type:       r.EventType,
			Timestamp:  r.Timestamp.Time,
			Details:    r.Details,
		})
	}
	return out, nil
}

func (p *PostgresStore) ListWorkflows(ctx context.Context, filter ListFilter) ([]*Workflow, error) {
	limit := int32(filter.Limit)
	if limit <= 0 {
		limit = 100
	}
	var status *string
	if filter.Status != "" {
		s := string(filter.Status)
		status = &s
	}
	rows, err := p.queries.ListWorkflows(ctx, db.ListWorkflowsParams{
		Status: status,
		LimitN: limit,
	})
	if err != nil {
		return nil, fmt.Errorf("list workflows: %w", err)
	}
	out := make([]*Workflow, 0, len(rows))
	for _, r := range rows {
		wf := workflowFromRow(r)
		out = append(out, &wf)
	}
	return out, nil
}

func (p *PostgresStore) InsertTimer(ctx context.Context, t Timer) error {
	if err := p.queries.InsertTimer(ctx, db.InsertTimerParams{
		TimerID:    t.TimerID,
		WorkflowID: t.WorkflowID,
		FireAt:     pgtype.Timestamptz{Time: t.FireAt, Valid: true},
	}); err != nil {
		return fmt.Errorf("insert timer: %w", err)
	}
	return nil
}

// FetchDueTimers atomically claims and marks-fired up to limit timers
// whose fire_at is past. The SELECT FOR UPDATE SKIP LOCKED inside a
// transaction guarantees no two callers ever claim the same row.
func (p *PostgresStore) FetchDueTimers(ctx context.Context, limit int) ([]Timer, error) {
	if limit <= 0 {
		limit = 64
	}
	tx, err := p.pool.Begin(ctx)
	if err != nil {
		return nil, fmt.Errorf("begin tx: %w", err)
	}
	defer tx.Rollback(ctx)

	q := p.queries.WithTx(tx)
	rows, err := q.FetchDueTimers(ctx, int32(limit))
	if err != nil {
		return nil, fmt.Errorf("fetch due timers: %w", err)
	}
	out := make([]Timer, 0, len(rows))
	for _, r := range rows {
		if err := q.MarkTimerFired(ctx, r.TimerID); err != nil {
			return nil, fmt.Errorf("mark fired %s: %w", r.TimerID, err)
		}
		out = append(out, timerFromRow(r))
	}
	if err := tx.Commit(ctx); err != nil {
		return nil, fmt.Errorf("commit: %w", err)
	}
	return out, nil
}

func (p *PostgresStore) ListPendingTimers(ctx context.Context) ([]Timer, error) {
	rows, err := p.queries.GetPendingTimers(ctx)
	if err != nil {
		return nil, fmt.Errorf("list pending timers: %w", err)
	}
	out := make([]Timer, 0, len(rows))
	for _, r := range rows {
		out = append(out, timerFromRow(r))
	}
	return out, nil
}

func timerFromRow(r db.Timer) Timer {
	return Timer{
		TimerID:    r.TimerID,
		WorkflowID: r.WorkflowID,
		FireAt:     r.FireAt.Time,
		Fired:      r.Fired,
		CreatedAt:  r.CreatedAt.Time,
	}
}

// querier is the subset of pgx that both *pgxpool.Pool and pgx.Tx satisfy
// for read-only existence checks.
type querier interface {
	QueryRow(ctx context.Context, sql string, args ...any) pgx.Row
}

func assertWorkflowExists(ctx context.Context, q querier, workflowID string) error {
	var exists bool
	err := q.QueryRow(ctx,
		`SELECT EXISTS(SELECT 1 FROM workflow_executions WHERE workflow_id = $1)`,
		workflowID,
	).Scan(&exists)
	if err != nil {
		return fmt.Errorf("check workflow exists: %w", err)
	}
	if !exists {
		return ErrWorkflowNotFound
	}
	return nil
}

func workflowFromRow(r db.WorkflowExecution) Workflow {
	wf := Workflow{
		WorkflowID: r.WorkflowID,
		RunID:      r.RunID,
		Name:       r.Name,
		Status:     WorkflowStatus(r.Status),
		Input:      r.Input,
		Result:     r.Result,
		Error:      r.Error,
		StartTime:  r.StartTime.Time,
		Version:    int(r.Version),
	}
	if r.EndTime.Valid {
		t := r.EndTime.Time
		wf.EndTime = &t
	}
	return wf
}
