// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendEvent = `-- name: AppendEvent :one
INSERT INTO workflow_events (workflow_id, idx, event_type, timestamp, details)
VALUES (
    $1,
    (SELECT COALESCE(MAX(idx), 0) + 1
       FROM workflow_events
       WHERE workflow_id = $1),
    $2,
    NOW(),
    $3
)
RETURNING idx, timestamp
`

type AppendEventParams struct {
	WorkflowID string
	EventType  string
	Details    []byte
}

type AppendEventRow struct {
	Idx       int64
	Timestamp pgtype.Timestamptz
}

// AppendEvent inserts the next event for a workflow. The idx is derived
// from the current MAX(idx) for that workflow; the (workflow_id, idx)
// primary key guarantees monotonicity. Concurrent appends to the same
// workflow may collide on idx; callers must serialize per workflow or
// retry on unique-violation.
func (q *Queries) AppendEvent(ctx context.Context, arg AppendEventParams) (AppendEventRow, error) {
	row := q.db.QueryRow(ctx, appendEvent, arg.WorkflowID, arg.EventType, arg.Details)
	var i AppendEventRow
	err := row.Scan(&i.Idx, &i.Timestamp)
	return i, err
}

const getHistory = `-- name: GetHistory :many
SELECT workflow_id, idx, event_type, timestamp, details
FROM workflow_events
WHERE workflow_id = $1
ORDER BY idx ASC
`

func (q *Queries) GetHistory(ctx context.Context, workflowID string) ([]WorkflowEvent, error) {
	rows, err := q.db.Query(ctx, getHistory, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkflowEvent{}
	for rows.Next() {
		var i WorkflowEvent
		if err := rows.Scan(
			&i.WorkflowID,
			&i.Idx,
			&i.EventType,
			&i.Timestamp,
			&i.Details,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
