// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Task struct {
	TaskToken         string
	WorkflowID        string
	Kind              string
	ActivityName      *string
	Input             []byte
	Status            string
	ClaimToken        *string
	VisibilityTimeout pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
}

type Timer struct {
	TimerID    string
	WorkflowID string
	FireAt     pgtype.Timestamptz
	Fired      bool
	CreatedAt  pgtype.Timestamptz
}

type WorkflowEvent struct {
	WorkflowID string
	Idx        int64
	EventType  string
	Timestamp  pgtype.Timestamptz
	Details    []byte
}

type WorkflowExecution struct {
	WorkflowID string
	RunID      string
	Name       string
	Status     string
	Input      []byte
	Result     []byte
	Error      string
	StartTime  pgtype.Timestamptz
	EndTime    pgtype.Timestamptz
	Version    int32
}
