// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// AppendEvent inserts the next event for a workflow. The idx is derived
	// from the current MAX(idx) for that workflow; the (workflow_id, idx)
	// primary key guarantees monotonicity. Concurrent appends to the same
	// workflow may collide on idx; callers must serialize per workflow or
	// retry on unique-violation.
	AppendEvent(ctx context.Context, arg AppendEventParams) (AppendEventRow, error)
	BumpVersion(ctx context.Context, workflowID string) error
	CompleteWorkflow(ctx context.Context, arg CompleteWorkflowParams) error
	CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) error
	GetHistory(ctx context.Context, workflowID string) ([]WorkflowEvent, error)
	GetWorkflow(ctx context.Context, workflowID string) (WorkflowExecution, error)
	ListWorkflows(ctx context.Context, arg ListWorkflowsParams) ([]WorkflowExecution, error)
}

var _ Querier = (*Queries)(nil)
