// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: timers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const fetchDueTimers = `-- name: FetchDueTimers :many
SELECT timer_id, workflow_id, fire_at, fired, created_at
FROM timers
WHERE NOT fired
  AND fire_at <= NOW()
ORDER BY fire_at
LIMIT $1
FOR UPDATE SKIP LOCKED
`

// FOR UPDATE SKIP LOCKED lets multiple engine replicas poll the same
// table without stepping on each other. Each row is claimed by exactly
// one caller until the transaction commits.
func (q *Queries) FetchDueTimers(ctx context.Context, limit int32) ([]Timer, error) {
	rows, err := q.db.Query(ctx, fetchDueTimers, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Timer{}
	for rows.Next() {
		var i Timer
		if err := rows.Scan(
			&i.TimerID,
			&i.WorkflowID,
			&i.FireAt,
			&i.Fired,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingTimers = `-- name: GetPendingTimers :many
SELECT timer_id, workflow_id, fire_at, fired, created_at
FROM timers
WHERE NOT fired
ORDER BY fire_at
`

// Used by TimerManager on startup to repopulate in-memory tracking
// for unfired timers persisted by a previous run.
func (q *Queries) GetPendingTimers(ctx context.Context) ([]Timer, error) {
	rows, err := q.db.Query(ctx, getPendingTimers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Timer{}
	for rows.Next() {
		var i Timer
		if err := rows.Scan(
			&i.TimerID,
			&i.WorkflowID,
			&i.FireAt,
			&i.Fired,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTimer = `-- name: InsertTimer :exec
INSERT INTO timers (timer_id, workflow_id, fire_at, fired)
VALUES ($1, $2, $3, FALSE)
`

type InsertTimerParams struct {
	TimerID    string
	WorkflowID string
	FireAt     pgtype.Timestamptz
}

func (q *Queries) InsertTimer(ctx context.Context, arg InsertTimerParams) error {
	_, err := q.db.Exec(ctx, insertTimer, arg.TimerID, arg.WorkflowID, arg.FireAt)
	return err
}

const markTimerFired = `-- name: MarkTimerFired :exec
UPDATE timers
SET fired = TRUE
WHERE timer_id = $1
`

func (q *Queries) MarkTimerFired(ctx context.Context, timerID string) error {
	_, err := q.db.Exec(ctx, markTimerFired, timerID)
	return err
}
