// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflows.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bumpVersion = `-- name: BumpVersion :exec
UPDATE workflow_executions
SET version = version + 1
WHERE workflow_id = $1
`

func (q *Queries) BumpVersion(ctx context.Context, workflowID string) error {
	_, err := q.db.Exec(ctx, bumpVersion, workflowID)
	return err
}

const completeWorkflow = `-- name: CompleteWorkflow :exec
UPDATE workflow_executions
SET status   = $2,
    result   = $3,
    error    = $4,
    end_time = NOW(),
    version  = version + 1
WHERE workflow_id = $1
`

type CompleteWorkflowParams struct {
	WorkflowID string
	Status     string
	Result     []byte
	Error      string
}

func (q *Queries) CompleteWorkflow(ctx context.Context, arg CompleteWorkflowParams) error {
	_, err := q.db.Exec(ctx, completeWorkflow,
		arg.WorkflowID,
		arg.Status,
		arg.Result,
		arg.Error,
	)
	return err
}

const createWorkflow = `-- name: CreateWorkflow :exec
INSERT INTO workflow_executions (
    workflow_id, run_id, name, status, input, start_time, version
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
`

type CreateWorkflowParams struct {
	WorkflowID string
	RunID      string
	Name       string
	Status     string
	Input      []byte
	StartTime  pgtype.Timestamptz
	Version    int32
}

func (q *Queries) CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) error {
	_, err := q.db.Exec(ctx, createWorkflow,
		arg.WorkflowID,
		arg.RunID,
		arg.Name,
		arg.Status,
		arg.Input,
		arg.StartTime,
		arg.Version,
	)
	return err
}

const getWorkflow = `-- name: GetWorkflow :one
SELECT workflow_id, run_id, name, status, input, result, error,
       start_time, end_time, version
FROM workflow_executions
WHERE workflow_id = $1
`

func (q *Queries) GetWorkflow(ctx context.Context, workflowID string) (WorkflowExecution, error) {
	row := q.db.QueryRow(ctx, getWorkflow, workflowID)
	var i WorkflowExecution
	err := row.Scan(
		&i.WorkflowID,
		&i.RunID,
		&i.Name,
		&i.Status,
		&i.Input,
		&i.Result,
		&i.Error,
		&i.StartTime,
		&i.EndTime,
		&i.Version,
	)
	return i, err
}

const listWorkflows = `-- name: ListWorkflows :many
SELECT workflow_id, run_id, name, status, input, result, error,
       start_time, end_time, version
FROM workflow_executions
WHERE ($1::text IS NULL OR status = $1::text)
ORDER BY start_time DESC
LIMIT $2
`

type ListWorkflowsParams struct {
	Status *string
	LimitN int32
}

func (q *Queries) ListWorkflows(ctx context.Context, arg ListWorkflowsParams) ([]WorkflowExecution, error) {
	rows, err := q.db.Query(ctx, listWorkflows, arg.Status, arg.LimitN)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkflowExecution{}
	for rows.Next() {
		var i WorkflowExecution
		if err := rows.Scan(
			&i.WorkflowID,
			&i.RunID,
			&i.Name,
			&i.Status,
			&i.Input,
			&i.Result,
			&i.Error,
			&i.StartTime,
			&i.EndTime,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
